# Generated by Django 5.0 on 2024-04-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anna', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
