# Generated by Django 5.0 on 2024-04-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anna', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='Tag',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
