# Generated by Django 5.0 on 2024-04-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anna', '0004_personal_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='footer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
