# Generated by Django 5.0 on 2024-04-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anna', '0005_personal_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Socials',
            },
        ),
    ]
