# Generated by Django 5.0.4 on 2024-04-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anna', '0006_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.CharField(choices=[('facebook', 'facebook'), ('gitlab', 'Git Lab'), ('github', 'Git Hub'), ('messenger', 'Messenger'), ('twitter', 'Twitter'), ('google', 'Google'), ('linkedin', 'LinkedIn'), ('youtube', 'Youtube'), ('instagram', 'Instagram'), ('pinterest', 'Pinterest'), ('snapchat-ghost', 'Snapchat Ghost'), ('skype', 'Skype'), ('android', 'Andriod'), ('dribbble', 'Dribble'), ('vimeo', 'Vimeo'), ('tumblr', 'Tumblr'), ('vine', 'Vine'), ('foursquare', 'Foursquare'), ('stumbleupon', 'Stumbleupon'), ('flickr', 'Flickr'), ('yahoo', 'Yahoo'), ('soundcloud', 'Soundcloud'), ('reddit', 'Reddit'), ('rss', 'Rss')], max_length=50),
        ),
    ]
