# Generated by Django 5.0 on 2024-04-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Projects')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'My Projects',
            },
        ),
    ]
