# Generated by Django 5.0 on 2024-04-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_design_developing'),
    ]

    operations = [
        migrations.CreateModel(
            name='External',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'External',
                'verbose_name_plural': 'External Details',
            },
        ),
    ]
